openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: /
paths:
  /api/health:
    get:
      tags:
      - Health
      summary: Get Health
      operationId: get_health_api_health_get
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/spacecraft:
    get:
      tags:
      - Spacecraft
      summary: Get Items
      operationId: get_items_api_spacecraft_get
      parameters:
      - name: page_number
        in: query
        required: false
        style: form
        explode: true
        schema:
          title: Page Number
          default: 0
      - name: page_size
        in: query
        required: false
        style: form
        explode: true
        schema:
          title: Page Size
          default: 100
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpacecraftPayload'
        "404":
          description: Endpoint not found
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - Spacecraft
      summary: Create Spacecraft
      operationId: create_spacecraft_api_spacecraft_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Spacecraft'
        required: true
      responses:
        "201":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        "404":
          description: Endpoint not found
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /api/spacecraft/{id}:
    get:
      tags:
      - Spacecraft
      summary: Get Spacecraft
      operationId: get_spacecraft_api_spacecraft__id__get
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          title: Id
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        "404":
          description: Endpoint not found
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - Spacecraft
      summary: Update Spacecraft
      operationId: update_spacecraft_api_spacecraft__id__put
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          title: Id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Spacecraft'
        required: true
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        "404":
          description: Endpoint not found
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - Spacecraft
      summary: Delete Spacecraft
      operationId: delete_spacecraft_api_spacecraft__id__delete
      parameters:
      - name: id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          title: Id
      responses:
        "204":
          description: Successful Response
        "404":
          description: Endpoint not found
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      properties:
        detail:
          title: Detail
          items:
            $ref: '#/components/schemas/ValidationError'
    Spacecraft:
      title: Spacecraft
      required:
      - appearances
      - id
      - name
      properties:
        id:
          title: Id
        name:
          title: Name
        description:
          title: Description
          anyOf:
          - {}
          - {}
        affiliation:
          title: Affiliation
          anyOf:
          - {}
          - {}
        dimensions:
          title: Dimensions
          anyOf:
          - {}
          - {}
        appearances:
          title: Appearances
    SpacecraftPayload:
      title: SpacecraftPayload
      required:
      - items
      properties:
        items:
          title: Items
          items:
            $ref: '#/components/schemas/Spacecraft'
        item_count:
          title: Item Count
          default: 0
        page_count:
          title: Page Count
          default: 0
        prev_page:
          title: Prev Page
          anyOf:
          - {}
          - {}
        next_page:
          title: Next Page
          anyOf:
          - {}
          - {}
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      properties:
        loc:
          title: Location
          items:
            anyOf:
            - {}
            - {}
        msg:
          title: Message
        type:
          title: Error Type
