# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Code Quality Checks

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  DATABASE_URL: ${{ vars.DATABASE_URL }}
  OIDC_CONFIG_URL: ${{ vars.OIDC_CONFIG_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Lint with Ruff
        run: |
          ruff check .
      - name: Format with Ruff
        run: |
          ruff format .
      - name: Test with pytest
        run: |
          pytest
